name: Build & Publish

on:
  push:
    tags: v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build the package
        run: npm run build-library

      - name: Publish tag to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish tag to GPR
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
